// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyBhbQAQZboBJd90lSqJNZuBOVcEOGJ3E',
    appId: '1:423685278731:web:bde8247c3b2698a12e8b0e',
    messagingSenderId: '423685278731',
    projectId: 'doctorapp-7e8b3',
    authDomain: 'doctorapp-7e8b3.firebaseapp.com',
    storageBucket: 'doctorapp-7e8b3.appspot.com',
    measurementId: 'G-HQEX6LQTFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyQqsOQNHRdQASw2zYC-8uGx2jLpFkbdw',
    appId: '1:423685278731:android:5901e1d036a552172e8b0e',
    messagingSenderId: '423685278731',
    projectId: 'doctorapp-7e8b3',
    storageBucket: 'doctorapp-7e8b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC66TrtGIhQz529lyN9cWN5f-AUd7uvu6M',
    appId: '1:423685278731:ios:9bc066f5e825b7102e8b0e',
    messagingSenderId: '423685278731',
    projectId: 'doctorapp-7e8b3',
    storageBucket: 'doctorapp-7e8b3.firebasestorage.app',
    iosBundleId: 'com.example.doctorPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC66TrtGIhQz529lyN9cWN5f-AUd7uvu6M',
    appId: '1:423685278731:ios:9bc066f5e825b7102e8b0e',
    messagingSenderId: '423685278731',
    projectId: 'doctorapp-7e8b3',
    storageBucket: 'doctorapp-7e8b3.firebasestorage.app',
    iosBundleId: 'com.example.doctorPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyBhbQAQZboBJd90lSqJNZuBOVcEOGJ3E',
    appId: '1:423685278731:web:767c5e00bb075e532e8b0e',
    messagingSenderId: '423685278731',
    projectId: 'doctorapp-7e8b3',
    authDomain: 'doctorapp-7e8b3.firebaseapp.com',
    storageBucket: 'doctorapp-7e8b3.firebasestorage.app',
    measurementId: 'G-2LYMM056XZ',
  );
}
